on: [push]
jobs:
  build:
    name: Run all tests with pytest inside the Python environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: 'latest' # any version from https://github.com/mamba-org/micromamba-releases
        environment-file: environment.yaml
        cache-environment: true
        init-shell: bash
        post-cleanup: 'all'
    - name: Setup poetry
      run: poetry install
    - name: Run tests
      run: pytest tests